version: '3.9'

services:
  api01: &api
    build: .
    image: sizebay-backend:latest
    container_name: api01
    hostname: api01
    environment:
      - DB_URL=jdbc:postgresql://db:5432/sizebay
      - DB_USER=sizebay
      - DB_PASSWORD=sizebay
      - JAVA_TOOL_OPTIONS=-Xmx110m -Xms110m -Xss256k -XX:+UseSerialGC -Djava.security.egd=file:/dev/./urandom
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.55'
          memory: '180MB'

  api02:
    <<: *api
    container_name: api02
    hostname: api02

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '70MB'

  db:
    image: postgres:latest
    hostname: db
    command: postgres -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c max_connections=200
    environment:
      - POSTGRES_PASSWORD=sizebay
      - POSTGRES_USER=sizebay
      - POSTGRES_DB=sizebay
    ports:
      - "5433:5432"
    volumes:
      - ./src/main/resources/db/script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '120MB'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sizebay -d sizebay"]
      interval: 5s
      timeout: 5s
      retries: 5